# Podman Compose file for Rocky Linux 9 with SELinux
# Run with: podman-compose up -d
# Or: podman compose up -d (if using podman-compose plugin)
#
# For rootless podman with ports 80/443, first run:
#   sudo sysctl -w net.ipv4.ip_unprivileged_port_start=80
# Or add to /etc/sysctl.d/podman-privileged-ports.conf for persistence

services:
  db:
    image: docker.io/library/postgres:16-alpine
    container_name: pricefeed-db
    environment:
      POSTGRES_USER: pricefeed
      POSTGRES_PASSWORD: pricefeed_dev
      POSTGRES_DB: pricefeed
    volumes:
      - pricefeed-data:/var/lib/postgresql/data:Z
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pricefeed -d pricefeed"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - pricefeed-net

  garage:
    image: docker.io/dxflrs/garage:v1.0.1
    container_name: pricefeed-garage
    restart: unless-stopped
    environment:
      GARAGE_RPC_SECRET: "${GARAGE_RPC_SECRET}"
    volumes:
      - garage-data:/var/lib/garage/data:Z
      - garage-meta:/var/lib/garage/meta:Z
      - ./garage.toml:/etc/garage.toml:ro,Z
    networks:
      - pricefeed-net
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3902/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pricefeed-app
    env_file:
      - .env
    environment:
      PORT: "8080"
      ENVIRONMENT: production
      ALLOWED_ORIGINS: "*"
      DATABASE_URL: postgres://pricefeed:pricefeed_dev@db:5432/pricefeed?sslmode=disable
      S3_ENDPOINT: garage:3900
    depends_on:
      db:
        condition: service_healthy
      garage:
        condition: service_started
    networks:
      - pricefeed-net

  npm:
    image: docker.io/jc21/nginx-proxy-manager:latest
    container_name: pricefeed-npm
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    volumes:
      - npm-data:/data:Z
      - npm-letsencrypt:/etc/letsencrypt:Z
    depends_on:
      - app
    networks:
      - pricefeed-net

volumes:
  pricefeed-data:
  npm-data:
  npm-letsencrypt:
  garage-data:
  garage-meta:

networks:
  pricefeed-net:
    driver: bridge
