# Podman Compose for Rocky Linux 9 VPS (no iptables required)
# All services run in a single pod, communicating via localhost
#
# Run with: podman-compose up -d

services:
  db:
    image: docker.io/library/postgres:16-alpine
    container_name: pricefeed-db
    environment:
      POSTGRES_USER: pricefeed
      POSTGRES_PASSWORD: pricefeed_dev
      POSTGRES_DB: pricefeed
    volumes:
      - pricefeed-data:/var/lib/postgresql/data:Z
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pricefeed -d pricefeed"]
      interval: 5s
      timeout: 5s
      retries: 5
    network_mode: host

  garage:
    image: docker.io/dxflrs/garage:v1.0.1
    container_name: pricefeed-garage
    restart: unless-stopped
    environment:
      GARAGE_RPC_SECRET: "${GARAGE_RPC_SECRET}"
    volumes:
      - garage-data:/var/lib/garage/data:Z
      - garage-meta:/var/lib/garage/meta:Z
      - ./garage.toml:/etc/garage.toml:ro,Z
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://127.0.0.1:3902/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    network_mode: host
    depends_on:
      db:
        condition: service_healthy

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pricefeed-app
    env_file:
      - .env
    environment:
      PORT: "8080"
      ENVIRONMENT: production
      ALLOWED_ORIGINS: "*"
      DATABASE_URL: postgres://pricefeed:pricefeed_dev@127.0.0.1:5432/pricefeed?sslmode=disable
      S3_ENDPOINT: 127.0.0.1:3900
    depends_on:
      db:
        condition: service_healthy
      garage:
        condition: service_started
    network_mode: host

  npm:
    image: docker.io/jc21/nginx-proxy-manager:latest
    container_name: pricefeed-npm
    restart: unless-stopped
    volumes:
      - npm-data:/data:Z
      - npm-letsencrypt:/etc/letsencrypt:Z
    depends_on:
      - app
    network_mode: host

volumes:
  pricefeed-data:
  npm-data:
  npm-letsencrypt:
  garage-data:
  garage-meta:
