-- Migration 003: Add all US states as regions
-- Cities will be added in subsequent migrations

INSERT INTO regions (name, state, zip_codes) VALUES
    ('Alabama', 'AL', ARRAY[]::TEXT[]),
    ('Alaska', 'AK', ARRAY[]::TEXT[]),
    ('Arizona', 'AZ', ARRAY[]::TEXT[]),
    ('Arkansas', 'AR', ARRAY[]::TEXT[]),
    ('California', 'CA', ARRAY[]::TEXT[]),
    ('Colorado', 'CO', ARRAY[]::TEXT[]),
    ('Connecticut', 'CT', ARRAY[]::TEXT[]),
    ('Delaware', 'DE', ARRAY[]::TEXT[]),
    ('Florida', 'FL', ARRAY[]::TEXT[]),
    ('Georgia', 'GA', ARRAY[]::TEXT[]),
    ('Hawaii', 'HI', ARRAY[]::TEXT[]),
    ('Idaho', 'ID', ARRAY[]::TEXT[]),
    ('Illinois', 'IL', ARRAY[]::TEXT[]),
    ('Indiana', 'IN', ARRAY[]::TEXT[]),
    ('Iowa', 'IA', ARRAY[]::TEXT[]),
    ('Kansas', 'KS', ARRAY[]::TEXT[]),
    ('Kentucky', 'KY', ARRAY[]::TEXT[]),
    ('Louisiana', 'LA', ARRAY[]::TEXT[]),
    ('Maine', 'ME', ARRAY[]::TEXT[]),
    ('Maryland', 'MD', ARRAY[]::TEXT[]),
    ('Massachusetts', 'MA', ARRAY[]::TEXT[]),
    ('Michigan', 'MI', ARRAY[]::TEXT[]),
    ('Minnesota', 'MN', ARRAY[]::TEXT[]),
    ('Mississippi', 'MS', ARRAY[]::TEXT[]),
    ('Missouri', 'MO', ARRAY[]::TEXT[]),
    ('Montana', 'MT', ARRAY[]::TEXT[]),
    ('Nebraska', 'NE', ARRAY[]::TEXT[]),
    ('Nevada', 'NV', ARRAY[]::TEXT[]),
    ('New Hampshire', 'NH', ARRAY[]::TEXT[]),
    ('New Jersey', 'NJ', ARRAY[]::TEXT[]),
    ('New Mexico', 'NM', ARRAY[]::TEXT[]),
    ('New York', 'NY', ARRAY[]::TEXT[]),
    ('North Carolina', 'NC', ARRAY[]::TEXT[]),
    ('North Dakota', 'ND', ARRAY[]::TEXT[]),
    ('Ohio', 'OH', ARRAY[]::TEXT[]),
    ('Oklahoma', 'OK', ARRAY[]::TEXT[]),
    ('Oregon', 'OR', ARRAY[]::TEXT[]),
    ('Pennsylvania', 'PA', ARRAY[]::TEXT[]),
    ('Rhode Island', 'RI', ARRAY[]::TEXT[]),
    ('South Carolina', 'SC', ARRAY[]::TEXT[]),
    ('South Dakota', 'SD', ARRAY[]::TEXT[]),
    ('Tennessee', 'TN', ARRAY[]::TEXT[]),
    ('Texas', 'TX', ARRAY[]::TEXT[]),
    ('Utah', 'UT', ARRAY[]::TEXT[]),
    ('Vermont', 'VT', ARRAY[]::TEXT[]),
    ('Virginia', 'VA', ARRAY[]::TEXT[]),
    ('Washington', 'WA', ARRAY[]::TEXT[]),
    ('West Virginia', 'WV', ARRAY[]::TEXT[]),
    ('Wisconsin', 'WI', ARRAY[]::TEXT[]),
    ('Wyoming', 'WY', ARRAY[]::TEXT[]),
    -- US Territories
    ('District of Columbia', 'DC', ARRAY[]::TEXT[]),
    ('Puerto Rico', 'PR', ARRAY[]::TEXT[]),
    ('Guam', 'GU', ARRAY[]::TEXT[]),
    ('US Virgin Islands', 'VI', ARRAY[]::TEXT[]),
    ('American Samoa', 'AS', ARRAY[]::TEXT[]),
    ('Northern Mariana Islands', 'MP', ARRAY[]::TEXT[])
ON CONFLICT DO NOTHING;
